// Generated by `pnpm ui:tokens` from docs/design/tokens.json. Do not edit by hand.
// Pixel values for code that needs a number (SVG sizes, icon props). CSS uses the variables.
export const SIZE_APP_ICON = 76;
export const SIZE_TAB_ITEM = 82;
export const SIZE_CONTROL = 44;
export const SIZE_WINDOW = 1240;
export const SIZE_DOCK_TILE = 56;
export const RADIUS_XS = 8;
export const RADIUS_SM = 12;
export const RADIUS_MD = 16;
export const RADIUS_LG = 20;
export const RADIUS_ICON = 22;
export const RADIUS_XL = 24;
export const RADIUS_WINDOW = 28;
export const RADIUS_PILL = 999;
export const RADIUS_DOCK = 26;
export const RADIUS_DOCK_TILE = 15;
export const SPACE_1 = 4;
export const SPACE_2 = 8;
export const SPACE_3 = 12;
export const SPACE_4 = 16;
export const SPACE_5 = 20;
export const SPACE_6 = 24;
export const SPACE_7 = 28;
export const SPACE_10 = 40;
