// `pnpm ui:tokens`: docs/design/tokens.json → src/styles/tokens.css (CSS variables, themed by
// data-theme and data-accent) and src/styles/theme.css (the Tailwind 4 theme that maps to them).
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const TOKENS = fileURLToPath(new URL('../../../docs/design/tokens.json', import.meta.url));
const OUT = fileURLToPath(new URL('../src/styles/', import.meta.url));
const HEADER = '/* Generated by `pnpm ui:tokens` from docs/design/tokens.json. Do not edit by hand. */\n';

interface Token {
  name: string;
  value: string | { glass: string; solid: string };
}
interface TypeStyle {
  name: string;
  fontSize: string;
  lineHeight: string;
  fontWeight: number;
  letterSpacing?: string;
}
interface Tokens {
  color: {
    tokens: Token[];
    accentSets: { sets: Array<Record<string, string>> };
    dock: { tokens: Array<{ name: string; value: string }> };
  };
  type: { families: { sans: string; mono: string }; groups: Array<{ styles: TypeStyle[] }> };
  spacing: { tokens: Array<{ name: string; value: string }> };
  radius: { tokens: Array<{ name: string; value: string }> };
  shadow: { tokens: Array<{ name: string; value: string }> };
  blur: { tokens: Array<{ name: string; value: string }> };
  size: { tokens: Array<{ name: string; value: string }> };
}

const ACCENT_KEYS = ['accent', 'accent-strong', 'accent-link', 'accent-tab', 'accent-wash'];

export function generate(tokens: Tokens): { tokensCss: string; themeCss: string; tokensTs: string } {
  const glass: string[] = [];
  const solid: string[] = [];
  for (const t of tokens.color.tokens) {
    if (typeof t.value === 'string') glass.push(`  --${t.name}: ${t.value};`);
    else {
      glass.push(`  --${t.name}: ${t.value.glass};`);
      solid.push(`  --${t.name}: ${t.value.solid};`);
    }
  }
  const scale = (group: { tokens: Array<{ name: string; value: string }> }) =>
    group.tokens.map((t) => `  --${t.name}: ${t.value};`);
  const types = tokens.type.groups.flatMap((g) => g.styles);

  const root = [
    ...glass,
    ...tokens.color.dock.tokens.map((t) => `  --${t.name}: ${t.value};`),
    `  --hl-font-sans: ${tokens.type.families.sans};`,
    `  --hl-font-mono: ${tokens.type.families.mono};`,
    ...scale(tokens.spacing),
    ...scale(tokens.radius),
    ...scale(tokens.shadow),
    ...scale(tokens.blur),
    ...scale(tokens.size),
  ];

  // Violet is the default accent (in :root); it also gets its own rule so any element (an avatar) can ask for it
  // inside a page with another accent.
  const byName = new Map(tokens.color.tokens.map((t) => [t.name, t.value]));
  const violet: Record<string, string> = { id: 'violet' };
  for (const k of ACCENT_KEYS) {
    const v = byName.get(k);
    violet[k] = typeof v === 'string' ? v : (v?.glass ?? '');
  }
  const accents = [violet, ...tokens.color.accentSets.sets].map(
    (set) => `[data-accent='${set.id}'] {\n${ACCENT_KEYS.map((k) => `  --${k}: ${set[k]};`).join('\n')}\n}`,
  );

  const tokensCss =
    HEADER +
    `:root,\n[data-theme='glass'] {\n${root.join('\n')}\n}\n\n` +
    `[data-theme='solid'] {\n${solid.join('\n')}\n}\n\n` +
    accents.join('\n\n') +
    '\n';

  const colors = tokens.color.tokens.map((t) => `  --color-${t.name}: var(--${t.name});`);
  const text = types.flatMap((s) => [
    `  --text-${s.name}: ${s.fontSize};`,
    `  --text-${s.name}--line-height: ${s.lineHeight};`,
    `  --text-${s.name}--font-weight: ${s.fontWeight};`,
    ...(s.letterSpacing ? [`  --text-${s.name}--letter-spacing: ${s.letterSpacing};`] : []),
  ]);
  const staticTheme = [
    // Only hlabs tokens exist: no default palette, radii, shadows or type scale.
    '  --color-*: initial;',
    '  --radius-*: initial;',
    '  --shadow-*: initial;',
    '  --blur-*: initial;',
    '  --text-*: initial;',
    '  --font-*: initial;',
    '  --color-transparent: transparent;',
    '  --color-current: currentColor;',
    `  --font-sans: ${tokens.type.families.sans};`,
    `  --font-mono: ${tokens.type.families.mono};`,
    ...text,
    ...tokens.radius.tokens.map((t) => `  --radius-${t.name.replace(/^radius-/, '')}: ${t.value};`),
    ...tokens.shadow.tokens.map((t) => `  --shadow-${t.name.replace(/^shadow-/, '')}: ${t.value};`),
    ...tokens.blur.tokens.map((t) => `  --blur-${t.name.replace(/^blur-/, '')}: ${t.value};`),
    ...tokens.size.tokens.map((t) => `  --spacing-${t.name.replace(/^size-/, '')}: ${t.value};`),
  ];
  const themeCss =
    HEADER +
    '/* Tailwind 4 theme: bg-surface-window, text-ink-muted, rounded-window, text-title-1, h-control … */\n' +
    `@theme {\n${staticTheme.join('\n')}\n}\n\n` +
    `@theme inline {\n${colors.join('\n')}\n}\n`;

  const px = (v: string) => Number.parseFloat(v);
  const constName = (name: string) => name.toUpperCase().replace(/-/g, '_');
  const numeric = [...tokens.size.tokens, ...tokens.radius.tokens, ...tokens.spacing.tokens]
    .map((t) => `export const ${constName(t.name)} = ${px(t.value)};`)
    .join('\n');
  const tokensTs =
    HEADER.replace('/*', '//').replace(' */', '') +
    '// Pixel values for code that needs a number (SVG sizes, icon props). CSS uses the variables.\n' +
    numeric +
    '\n';

  return { tokensCss, themeCss, tokensTs };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const { tokensCss, themeCss, tokensTs } = generate(JSON.parse(readFileSync(TOKENS, 'utf8')) as Tokens);
  writeFileSync(`${OUT}tokens.css`, tokensCss);
  writeFileSync(`${OUT}theme.css`, themeCss);
  writeFileSync(`${OUT}../lib/tokens.ts`, tokensTs);
  console.warn('ui:tokens: wrote src/styles/tokens.css, src/styles/theme.css and src/lib/tokens.ts');
}

export const TOKENS_PATH = TOKENS;
