/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as FilesRouteImport } from './routes/files'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as StoreRouteImport } from './routes/store'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as AppsAppIdRouteImport } from './routes/apps.$appId'
import { Route as DevUiRouteImport } from './routes/dev/ui'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginCodeRouteImport } from './routes/login.code'
import { Route as LoginLockedRouteImport } from './routes/login.locked'
import { Route as LoginPasswordRouteImport } from './routes/login.password'
import { Route as LoginUsernameRouteImport } from './routes/login.username'
import { Route as LoginUsersRouteImport } from './routes/login.users'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsSectionRouteImport } from './routes/settings.$section'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as SetupStepRouteImport } from './routes/setup.$step'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as StoreSearchRouteImport } from './routes/store.search'
import { Route as AppsAppIdLogsRouteImport } from './routes/apps_.$appId.logs'
import { Route as AppsAppIdSettingsRouteImport } from './routes/apps_.$appId.settings'
import { Route as SettingsAccountTwoFactorRouteImport } from './routes/settings.account.two-factor'
import { Route as StoreCategoryCategoryRouteImport } from './routes/store.category.$category'
import { Route as StoreCollectionCollectionIdRouteImport } from './routes/store.collection.$collectionId'
import { Route as StoreAppAppIdRouteImport } from './routes/store_.app.$appId'
import { Route as StoreInstallAppIdRouteImport } from './routes/store_.install.$appId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdRoute = AppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCodeRoute = LoginCodeRouteImport.update({
  id: '/login/code',
  path: '/login/code',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginLockedRoute = LoginLockedRouteImport.update({
  id: '/login/locked',
  path: '/login/locked',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPasswordRoute = LoginPasswordRouteImport.update({
  id: '/login/password',
  path: '/login/password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginUsernameRoute = LoginUsernameRouteImport.update({
  id: '/login/username',
  path: '/login/username',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginUsersRoute = LoginUsersRouteImport.update({
  id: '/login/users',
  path: '/login/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SettingsRoute,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const SetupStepRoute = SetupStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => SetupRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreSearchRoute = StoreSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => StoreRoute,
} as any)
const AppsAppIdLogsRoute = AppsAppIdLogsRouteImport.update({
  id: '/apps_/$appId/logs',
  path: '/apps/$appId/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdSettingsRoute = AppsAppIdSettingsRouteImport.update({
  id: '/apps_/$appId/settings',
  path: '/apps/$appId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountTwoFactorRoute =
  SettingsAccountTwoFactorRouteImport.update({
    id: '/account/two-factor',
    path: '/account/two-factor',
    getParentRoute: () => SettingsRoute,
  } as any)
const StoreCategoryCategoryRoute = StoreCategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCollectionCollectionIdRoute =
  StoreCollectionCollectionIdRouteImport.update({
    id: '/collection/$collectionId',
    path: '/collection/$collectionId',
    getParentRoute: () => StoreRoute,
  } as any)
const StoreAppAppIdRoute = StoreAppAppIdRouteImport.update({
  id: '/store_/app/$appId',
  path: '/store/app/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreInstallAppIdRoute = StoreInstallAppIdRouteImport.update({
  id: '/store_/install/$appId',
  path: '/store/install/$appId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/files': typeof FilesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRouteWithChildren
  '/store': typeof StoreRouteWithChildren
  '/trust': typeof TrustRoute
  '/usage': typeof UsageRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/dev/ui': typeof DevUiRoute
  '/login/code': typeof LoginCodeRoute
  '/login/locked': typeof LoginLockedRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/username': typeof LoginUsernameRoute
  '/login/users': typeof LoginUsersRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/setup/$step': typeof SetupStepRoute
  '/store/search': typeof StoreSearchRoute
  '/login/': typeof LoginIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/store/': typeof StoreIndexRoute
  '/apps/$appId/logs': typeof AppsAppIdLogsRoute
  '/apps/$appId/settings': typeof AppsAppIdSettingsRoute
  '/settings/account/two-factor': typeof SettingsAccountTwoFactorRoute
  '/store/category/$category': typeof StoreCategoryCategoryRoute
  '/store/collection/$collectionId': typeof StoreCollectionCollectionIdRoute
  '/store/app/$appId': typeof StoreAppAppIdRoute
  '/store/install/$appId': typeof StoreInstallAppIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/files': typeof FilesRoute
  '/trust': typeof TrustRoute
  '/usage': typeof UsageRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/dev/ui': typeof DevUiRoute
  '/login/code': typeof LoginCodeRoute
  '/login/locked': typeof LoginLockedRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/username': typeof LoginUsernameRoute
  '/login/users': typeof LoginUsersRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/setup/$step': typeof SetupStepRoute
  '/store/search': typeof StoreSearchRoute
  '/login': typeof LoginIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/setup': typeof SetupIndexRoute
  '/store': typeof StoreIndexRoute
  '/apps/$appId/logs': typeof AppsAppIdLogsRoute
  '/apps/$appId/settings': typeof AppsAppIdSettingsRoute
  '/settings/account/two-factor': typeof SettingsAccountTwoFactorRoute
  '/store/category/$category': typeof StoreCategoryCategoryRoute
  '/store/collection/$collectionId': typeof StoreCollectionCollectionIdRoute
  '/store/app/$appId': typeof StoreAppAppIdRoute
  '/store/install/$appId': typeof StoreInstallAppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/files': typeof FilesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRouteWithChildren
  '/store': typeof StoreRouteWithChildren
  '/trust': typeof TrustRoute
  '/usage': typeof UsageRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/dev/ui': typeof DevUiRoute
  '/login/code': typeof LoginCodeRoute
  '/login/locked': typeof LoginLockedRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/username': typeof LoginUsernameRoute
  '/login/users': typeof LoginUsersRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/setup/$step': typeof SetupStepRoute
  '/store/search': typeof StoreSearchRoute
  '/login/': typeof LoginIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/store/': typeof StoreIndexRoute
  '/apps_/$appId/logs': typeof AppsAppIdLogsRoute
  '/apps_/$appId/settings': typeof AppsAppIdSettingsRoute
  '/settings/account/two-factor': typeof SettingsAccountTwoFactorRoute
  '/store/category/$category': typeof StoreCategoryCategoryRoute
  '/store/collection/$collectionId': typeof StoreCollectionCollectionIdRoute
  '/store_/app/$appId': typeof StoreAppAppIdRoute
  '/store_/install/$appId': typeof StoreInstallAppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backups'
    | '/files'
    | '/settings'
    | '/setup'
    | '/store'
    | '/trust'
    | '/usage'
    | '/apps/$appId'
    | '/dev/ui'
    | '/login/code'
    | '/login/locked'
    | '/login/password'
    | '/login/username'
    | '/login/users'
    | '/settings/$section'
    | '/setup/$step'
    | '/store/search'
    | '/login/'
    | '/settings/'
    | '/setup/'
    | '/store/'
    | '/apps/$appId/logs'
    | '/apps/$appId/settings'
    | '/settings/account/two-factor'
    | '/store/category/$category'
    | '/store/collection/$collectionId'
    | '/store/app/$appId'
    | '/store/install/$appId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backups'
    | '/files'
    | '/trust'
    | '/usage'
    | '/apps/$appId'
    | '/dev/ui'
    | '/login/code'
    | '/login/locked'
    | '/login/password'
    | '/login/username'
    | '/login/users'
    | '/settings/$section'
    | '/setup/$step'
    | '/store/search'
    | '/login'
    | '/settings'
    | '/setup'
    | '/store'
    | '/apps/$appId/logs'
    | '/apps/$appId/settings'
    | '/settings/account/two-factor'
    | '/store/category/$category'
    | '/store/collection/$collectionId'
    | '/store/app/$appId'
    | '/store/install/$appId'
  id:
    | '__root__'
    | '/'
    | '/backups'
    | '/files'
    | '/settings'
    | '/setup'
    | '/store'
    | '/trust'
    | '/usage'
    | '/apps/$appId'
    | '/dev/ui'
    | '/login/code'
    | '/login/locked'
    | '/login/password'
    | '/login/username'
    | '/login/users'
    | '/settings/$section'
    | '/setup/$step'
    | '/store/search'
    | '/login/'
    | '/settings/'
    | '/setup/'
    | '/store/'
    | '/apps_/$appId/logs'
    | '/apps_/$appId/settings'
    | '/settings/account/two-factor'
    | '/store/category/$category'
    | '/store/collection/$collectionId'
    | '/store_/app/$appId'
    | '/store_/install/$appId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupsRoute: typeof BackupsRoute
  FilesRoute: typeof FilesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRouteWithChildren
  StoreRoute: typeof StoreRouteWithChildren
  TrustRoute: typeof TrustRoute
  UsageRoute: typeof UsageRoute
  AppsAppIdRoute: typeof AppsAppIdRoute
  DevUiRoute: typeof DevUiRoute
  LoginCodeRoute: typeof LoginCodeRoute
  LoginLockedRoute: typeof LoginLockedRoute
  LoginPasswordRoute: typeof LoginPasswordRoute
  LoginUsernameRoute: typeof LoginUsernameRoute
  LoginUsersRoute: typeof LoginUsersRoute
  LoginIndexRoute: typeof LoginIndexRoute
  AppsAppIdLogsRoute: typeof AppsAppIdLogsRoute
  AppsAppIdSettingsRoute: typeof AppsAppIdSettingsRoute
  StoreAppAppIdRoute: typeof StoreAppAppIdRoute
  StoreInstallAppIdRoute: typeof StoreInstallAppIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/code': {
      id: '/login/code'
      path: '/login/code'
      fullPath: '/login/code'
      preLoaderRoute: typeof LoginCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/locked': {
      id: '/login/locked'
      path: '/login/locked'
      fullPath: '/login/locked'
      preLoaderRoute: typeof LoginLockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/password': {
      id: '/login/password'
      path: '/login/password'
      fullPath: '/login/password'
      preLoaderRoute: typeof LoginPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/username': {
      id: '/login/username'
      path: '/login/username'
      fullPath: '/login/username'
      preLoaderRoute: typeof LoginUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/users': {
      id: '/login/users'
      path: '/login/users'
      fullPath: '/login/users'
      preLoaderRoute: typeof LoginUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/$step': {
      id: '/setup/$step'
      path: '/$step'
      fullPath: '/setup/$step'
      preLoaderRoute: typeof SetupStepRouteImport
      parentRoute: typeof SetupRoute
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/search': {
      id: '/store/search'
      path: '/search'
      fullPath: '/store/search'
      preLoaderRoute: typeof StoreSearchRouteImport
      parentRoute: typeof StoreRoute
    }
    '/apps_/$appId/logs': {
      id: '/apps_/$appId/logs'
      path: '/apps/$appId/logs'
      fullPath: '/apps/$appId/logs'
      preLoaderRoute: typeof AppsAppIdLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps_/$appId/settings': {
      id: '/apps_/$appId/settings'
      path: '/apps/$appId/settings'
      fullPath: '/apps/$appId/settings'
      preLoaderRoute: typeof AppsAppIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account/two-factor': {
      id: '/settings/account/two-factor'
      path: '/account/two-factor'
      fullPath: '/settings/account/two-factor'
      preLoaderRoute: typeof SettingsAccountTwoFactorRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/store/category/$category': {
      id: '/store/category/$category'
      path: '/category/$category'
      fullPath: '/store/category/$category'
      preLoaderRoute: typeof StoreCategoryCategoryRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/collection/$collectionId': {
      id: '/store/collection/$collectionId'
      path: '/collection/$collectionId'
      fullPath: '/store/collection/$collectionId'
      preLoaderRoute: typeof StoreCollectionCollectionIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store_/app/$appId': {
      id: '/store_/app/$appId'
      path: '/store/app/$appId'
      fullPath: '/store/app/$appId'
      preLoaderRoute: typeof StoreAppAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/install/$appId': {
      id: '/store_/install/$appId'
      path: '/store/install/$appId'
      fullPath: '/store/install/$appId'
      preLoaderRoute: typeof StoreInstallAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsSectionRoute: typeof SettingsSectionRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsAccountTwoFactorRoute: typeof SettingsAccountTwoFactorRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSectionRoute: SettingsSectionRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsAccountTwoFactorRoute: SettingsAccountTwoFactorRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface SetupRouteChildren {
  SetupStepRoute: typeof SetupStepRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupStepRoute: SetupStepRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

interface StoreRouteChildren {
  StoreSearchRoute: typeof StoreSearchRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreCategoryCategoryRoute: typeof StoreCategoryCategoryRoute
  StoreCollectionCollectionIdRoute: typeof StoreCollectionCollectionIdRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreSearchRoute: StoreSearchRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreCategoryCategoryRoute: StoreCategoryCategoryRoute,
  StoreCollectionCollectionIdRoute: StoreCollectionCollectionIdRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupsRoute: BackupsRoute,
  FilesRoute: FilesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRouteWithChildren,
  StoreRoute: StoreRouteWithChildren,
  TrustRoute: TrustRoute,
  UsageRoute: UsageRoute,
  AppsAppIdRoute: AppsAppIdRoute,
  DevUiRoute: DevUiRoute,
  LoginCodeRoute: LoginCodeRoute,
  LoginLockedRoute: LoginLockedRoute,
  LoginPasswordRoute: LoginPasswordRoute,
  LoginUsernameRoute: LoginUsernameRoute,
  LoginUsersRoute: LoginUsersRoute,
  LoginIndexRoute: LoginIndexRoute,
  AppsAppIdLogsRoute: AppsAppIdLogsRoute,
  AppsAppIdSettingsRoute: AppsAppIdSettingsRoute,
  StoreAppAppIdRoute: StoreAppAppIdRoute,
  StoreInstallAppIdRoute: StoreInstallAppIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
