/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as FilesRouteImport } from './routes/files'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as StoreRouteImport } from './routes/store'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as DevUiRouteImport } from './routes/dev/ui'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginCodeRouteImport } from './routes/login.code'
import { Route as LoginLockedRouteImport } from './routes/login.locked'
import { Route as LoginPasswordRouteImport } from './routes/login.password'
import { Route as LoginUsernameRouteImport } from './routes/login.username'
import { Route as LoginUsersRouteImport } from './routes/login.users'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as SetupStepRouteImport } from './routes/setup.$step'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCodeRoute = LoginCodeRouteImport.update({
  id: '/login/code',
  path: '/login/code',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginLockedRoute = LoginLockedRouteImport.update({
  id: '/login/locked',
  path: '/login/locked',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPasswordRoute = LoginPasswordRouteImport.update({
  id: '/login/password',
  path: '/login/password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginUsernameRoute = LoginUsernameRouteImport.update({
  id: '/login/username',
  path: '/login/username',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginUsersRoute = LoginUsersRouteImport.update({
  id: '/login/users',
  path: '/login/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const SetupStepRoute = SetupStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => SetupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/files': typeof FilesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/store': typeof StoreRoute
  '/usage': typeof UsageRoute
  '/dev/ui': typeof DevUiRoute
  '/login/code': typeof LoginCodeRoute
  '/login/locked': typeof LoginLockedRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/username': typeof LoginUsernameRoute
  '/login/users': typeof LoginUsersRoute
  '/setup/$step': typeof SetupStepRoute
  '/login/': typeof LoginIndexRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/files': typeof FilesRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/usage': typeof UsageRoute
  '/dev/ui': typeof DevUiRoute
  '/login/code': typeof LoginCodeRoute
  '/login/locked': typeof LoginLockedRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/username': typeof LoginUsernameRoute
  '/login/users': typeof LoginUsersRoute
  '/setup/$step': typeof SetupStepRoute
  '/login': typeof LoginIndexRoute
  '/setup': typeof SetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/files': typeof FilesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/store': typeof StoreRoute
  '/usage': typeof UsageRoute
  '/dev/ui': typeof DevUiRoute
  '/login/code': typeof LoginCodeRoute
  '/login/locked': typeof LoginLockedRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/username': typeof LoginUsernameRoute
  '/login/users': typeof LoginUsersRoute
  '/setup/$step': typeof SetupStepRoute
  '/login/': typeof LoginIndexRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backups'
    | '/files'
    | '/settings'
    | '/setup'
    | '/store'
    | '/usage'
    | '/dev/ui'
    | '/login/code'
    | '/login/locked'
    | '/login/password'
    | '/login/username'
    | '/login/users'
    | '/setup/$step'
    | '/login/'
    | '/setup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backups'
    | '/files'
    | '/settings'
    | '/store'
    | '/usage'
    | '/dev/ui'
    | '/login/code'
    | '/login/locked'
    | '/login/password'
    | '/login/username'
    | '/login/users'
    | '/setup/$step'
    | '/login'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/backups'
    | '/files'
    | '/settings'
    | '/setup'
    | '/store'
    | '/usage'
    | '/dev/ui'
    | '/login/code'
    | '/login/locked'
    | '/login/password'
    | '/login/username'
    | '/login/users'
    | '/setup/$step'
    | '/login/'
    | '/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupsRoute: typeof BackupsRoute
  FilesRoute: typeof FilesRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRouteWithChildren
  StoreRoute: typeof StoreRoute
  UsageRoute: typeof UsageRoute
  DevUiRoute: typeof DevUiRoute
  LoginCodeRoute: typeof LoginCodeRoute
  LoginLockedRoute: typeof LoginLockedRoute
  LoginPasswordRoute: typeof LoginPasswordRoute
  LoginUsernameRoute: typeof LoginUsernameRoute
  LoginUsersRoute: typeof LoginUsersRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/code': {
      id: '/login/code'
      path: '/login/code'
      fullPath: '/login/code'
      preLoaderRoute: typeof LoginCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/locked': {
      id: '/login/locked'
      path: '/login/locked'
      fullPath: '/login/locked'
      preLoaderRoute: typeof LoginLockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/password': {
      id: '/login/password'
      path: '/login/password'
      fullPath: '/login/password'
      preLoaderRoute: typeof LoginPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/username': {
      id: '/login/username'
      path: '/login/username'
      fullPath: '/login/username'
      preLoaderRoute: typeof LoginUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/users': {
      id: '/login/users'
      path: '/login/users'
      fullPath: '/login/users'
      preLoaderRoute: typeof LoginUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/$step': {
      id: '/setup/$step'
      path: '/$step'
      fullPath: '/setup/$step'
      preLoaderRoute: typeof SetupStepRouteImport
      parentRoute: typeof SetupRoute
    }
  }
}

interface SetupRouteChildren {
  SetupStepRoute: typeof SetupStepRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupStepRoute: SetupStepRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupsRoute: BackupsRoute,
  FilesRoute: FilesRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRouteWithChildren,
  StoreRoute: StoreRoute,
  UsageRoute: UsageRoute,
  DevUiRoute: DevUiRoute,
  LoginCodeRoute: LoginCodeRoute,
  LoginLockedRoute: LoginLockedRoute,
  LoginPasswordRoute: LoginPasswordRoute,
  LoginUsernameRoute: LoginUsernameRoute,
  LoginUsersRoute: LoginUsersRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
