// A source's index.json (06 §Store index), generated by `pnpm store:build` and signed in CI.
import { APP_ID_PATTERN } from '@hlabs/shared';
import { z } from 'zod';

const appId = z.string().regex(APP_ID_PATTERN);

export const StoreIndex = z
  .object({
    schema: z.literal(1),
    source: z.object({ id: z.string().min(1), name: z.string().min(1) }).strict(),
    apps: z.array(
      z
        .object({
          id: appId,
          version: z.string(),
          revision: z.number().int().min(0),
          manifestUrl: z.string(),
          composeUrl: z.string(),
          logoUrl: z.string().nullable(),
          /** sha256 of the manifest and compose file bytes. */
          digest: z.string().regex(/^sha256:[a-f0-9]{64}$/),
          rank: z.number().int().optional(),
        })
        .strict(),
    ),
    featured: z.array(appId).optional(),
    collections: z.array(StoreCollection()).optional(),
  })
  .strict();
export type StoreIndex = z.output<typeof StoreIndex>;

function StoreCollection() {
  return z
    .object({
      /** For links ("See all"): lowercase letters, numbers and dashes. */
      id: z.string().regex(/^[a-z0-9][a-z0-9-]{0,39}$/),
      title: z.string().min(1).max(60),
      appIds: z.array(appId).min(1),
    })
    .strict();
}

/**
 * `store/curation.yml`: the built-in store's featured apps and rows on the store home (US-STORE-01) and the curated
 * order for "Popular" (US-STORE-04). Written into index.json by `pnpm store:build`.
 */
export const StoreCuration = z
  .object({
    featured: z.array(appId).default([]),
    collections: z.array(StoreCollection()).default([]),
    /** Curated order, most popular first; apps not listed follow A–Z (hlabs collects no usage data). */
    rank: z.array(appId).default([]),
  })
  .strict();
export type StoreCuration = z.output<typeof StoreCuration>;
