// A source's index.json (06 §Store index), generated by `pnpm store:build` and signed in CI.
import { APP_ID_PATTERN } from '@hlabs/shared';
import { z } from 'zod';

const appId = z.string().regex(APP_ID_PATTERN);

export const StoreIndex = z
  .object({
    schema: z.literal(1),
    source: z.object({ id: z.string().min(1), name: z.string().min(1) }).strict(),
    apps: z.array(
      z
        .object({
          id: appId,
          version: z.string(),
          revision: z.number().int().min(0),
          manifestUrl: z.string(),
          composeUrl: z.string(),
          logoUrl: z.string().nullable(),
          /** sha256 of the manifest and compose file bytes. */
          digest: z.string().regex(/^sha256:[a-f0-9]{64}$/),
          rank: z.number().int().optional(),
        })
        .strict(),
    ),
    featured: z.array(appId).optional(),
    collections: z.array(z.object({ title: z.string(), appIds: z.array(appId) }).strict()).optional(),
  })
  .strict();
export type StoreIndex = z.output<typeof StoreIndex>;
