// Settings › Account (09-account-people.md).
export const accountCopy = {
  logOut: 'Log out',
  roles: { admin: 'Admin', member: 'Member' },
  who: (username: string, role: string) => `${username} · ${role}`,
  editProfile: 'Edit profile',
  profileTitle: 'Edit profile',
  displayName: 'Display name',
  enterName: 'Enter a name',
  username: 'Username',
  usernameHint: "Usernames can't be changed.",
  avatarColor: 'Avatar colour',
  colors: { violet: 'Violet', mint: 'Mint', amber: 'Amber', rose: 'Rose' },
  language: 'Language',
  languages: { en: 'English' },
  cancel: 'Cancel',
  save: 'Save',
  profileUpdated: 'Profile updated',
  saveFailed: "Couldn't save your profile. Try again.",
  unreachable: "Can't reach hlabs right now. Try again in a moment.",
  security: 'Security',
  password: 'Password',
  passwordSetUp: 'Changed when you set up hlabs',
  passwordChangedAgo: (ago: string) => `Changed ${ago}`,
  change: 'Change',
  changePasswordTitle: 'Change password',
  currentPassword: 'Current password',
  newPassword: 'New password',
  confirmPassword: 'Confirm new password',
  strong: 'Strong · at least 12 characters',
  tooShort: 'Too short · at least 12 characters',
  signOutOthers: 'Sign out my other devices',
  changePassword: 'Change password',
  passwordChanged: 'Password changed. Your other devices are signed out.',
  changeFailed: "Couldn't change your password. Check the fields and try again.",
  wrongCurrent: "That's not your current password",
  tooCommon: 'This password is too common. Try a longer phrase.',
  unchanged: "Choose a password you haven't used here",
  noMatch: "Passwords don't match",
  tooManyAttempts: (minutes: number) =>
    `Too many attempts. Try again in ${minutes} ${minutes === 1 ? 'minute' : 'minutes'}.`,
  twoFactor: 'Two-factor login',
  twoFactorOn: 'On · authenticator app',
  twoFactorOff: 'Off',
  on: 'On',
  manage: 'Manage',
  manageTwoFactor: 'Manage two-factor login',
  turnOn: 'Turn on',
  turnOnTwoFactor: 'Turn on two-factor login',
  recoveryCodes: 'Recovery codes',
  unusedOf: (n: number) => `${n} of 10 unused`,
  recoveryTitle: (n: number) => `Recovery codes · ${n} of 10 unused`,
  runningLow: 'Running low',
  view: 'View',
  viewRecoveryCodes: 'View recovery codes',
  authenticatorApp: 'Authenticator app',
  addedAtSetup: 'Added when you set up hlabs',
  addedOn: (date: string) => `Added ${date}`,
  done: 'Done',
  codesHelp: 'Each code works once if you lose your phone. Keep them somewhere safe, like a password manager.',
  codesList: 'Recovery codes',
  used: 'Used',
  hiddenCode: 'Hidden code',
  download: 'Download',
  print: 'Print',
  seeAgain: 'Make new codes to see them again',
  makeNewCodes: 'Make new codes',
  moveToNewPhone: 'Move to a new phone',
  moveIntro: 'Enter your password to set up two-factor login on your new phone.',
  scanTitle: 'Scan with your new phone',
  scanLead: 'Scan the QR code with your authenticator app, then enter the 6-digit code it shows.',
  confirm: 'Confirm',
  moved: 'Two-factor moved to your new phone',
  turnOnIntro: 'Enter your password to turn on two-factor login.',
  turnOnLead: 'Scan the QR code with your authenticator app, then enter the 6-digit code it shows.',
  turnOnScanTitle: 'Scan with your phone',
  turnOff: 'Turn off two-factor…',
  turnOffTitle: 'Turn off two-factor login?',
  turnOffWarning: 'Anyone with your password will be able to log in.',
  turnOffConfirm: 'Turn off',
  codeOrRecovery: '6-digit code or recovery code',
  wrongCodeOrRecovery: "That code didn't work. Use the code in your app now, or an unused recovery code.",
  requiredByAdmin: 'Your admin requires two-factor login.',
  turnedOff: 'Two-factor login is off. Your other devices are signed out.',
  oldCodesStop: 'Your old codes will stop working.',
  yourPassword: 'Your password',
  wrongPassword: "That's not your password",
  somethingWrong: 'Something went wrong. Try again.',
  devices: 'Signed-in devices',
  thisDevice: 'This device',
  signOut: 'Sign out',
  signOutDevice: (device: string) => `Sign out ${device}`,
  signedOut: (device: string) => `Signed out ${device}`,
  signOutFailed: (device: string) => `Couldn't sign out ${device}. Try again.`,
  deviceLine: (device: string, browser: string) => `${device} · ${browser}`,
  seenLine: (network: string, seen: string) => `${network} · ${seen}`,
  activeNow: 'active now',
  unknownDevice: 'Unknown device',
  unknownBrowser: 'Browser',
  networks: { tailscale: 'Tailscale', home: 'Home network', local: 'This computer', internet: 'Internet' },
} as const;
