// Settings › Engine & startup (10-system-settings.md). Sentence case, plain words.
export const engineCopy = {
  status: {
    running: 'Engine running',
    stopped: 'Engine stopped',
    starting: 'Starting…',
    missing: 'No engine',
  },
  containerEngine: 'Container engine',
  names: {
    orbstack: 'OrbStack',
    'docker-desktop': 'Docker Desktop',
    colima: 'Colima',
    'docker-engine': 'Docker Engine',
  },
  installedByHlabs: 'Installed by hlabs · open source',
  inUse: 'In use',
  inUseVersion: (version: string) => `In use · Docker ${version}`,
  stopped: 'Stopped',
  foundMac: 'Found on this Mac',
  foundComputer: 'Found on this computer',
  notInstalled: 'Not installed',
  switch: 'Switch…',
  restart: 'Restart engine',
  resources: 'Resources for apps',
  resourcesNote: 'macOS only, applied after a restart',
  cpus: 'CPU cores',
  memory: 'Memory',
  disk: 'Disk',
  gb: (n: number) => `${n} GB`,
  unknown: '—',
  cpuRange: (max: number) => `1 to ${max} cores`,
  gbRange: (min: number, max: number) => `${min} to ${max} GB`,
  apply: 'Apply and restart engine',
  changeIn: (engine: string) => `Change this in ${engine}'s settings`,
  startup: 'Startup',
  startAtLogin: 'Start hlabs when I log in',
  startAtLoginNote: 'Runs from the menu bar',
  autostartApps: 'Start apps automatically',
  autostartAppsNote: 'Apps set to "Start automatically" come back after a restart',
  keepAwake: 'Keep this computer awake',
  keepAwakeNote: 'Prevents sleep while apps are running; the display can still turn off',
  saveFailed: "Couldn't save that. Try again.",
  applyFailed: "Couldn't apply the new resources. Check the values and try again.",
  start: 'Start engine',
  restartTitle: 'Restart the container engine?',
  restartBody: 'All apps stop for about a minute.',
  restartConfirm: 'Restart',
  restarting: 'Restarting the engine',
  notBack: "The engine didn't come back. Start it again, or restart this computer.",
  restartFailed: "Couldn't restart the engine. Try again.",
  waitFor: (job: string) => `Wait for ${job} to finish`,
  jobs: {
    system_update: 'the hlabs update',
    restore: 'the restore',
    move_all_data: 'the data move',
    engine_switch: 'the engine switch',
    rename_host: 'the rename',
    factory_reset: 'the factory reset',
  } as Record<string, string>,
} as const;
