// Home (04-home.md). Sentence case, plain words.
export const homeCopy = {
  title: 'hlabs — Home',
  widgets: 'Widgets',
  apps: 'Apps',
  openApp: (name: string) => `Open ${name}`,
  installApp: 'Install app',
  storage: 'Storage',
  /** The Live usage widget (US-HOME-02, phase 4). */
  liveUsage: 'Live usage',
  cpu: 'CPU',
  memory: 'Memory',
  memoryUsedOf: (used: string, total: string) => `${used} / ${total}`,
  leftOf: (total: string) => `left of ${total}`,
  appsUsage: 'Apps',
  system: 'System',
  couldntLoad: "Couldn't load",
  myFiles: 'My files',
  inHomeFolder: 'in your Home folder',
  calculating: 'Calculating…',
  lastPhotoBackup: (ago: string) => `Last photo backup from your phone: ${ago}`,
  sharedBy: (admin: string) => `Shared with you by ${admin}`,
  sharedWithYou: 'Shared with you',
  appsAllRunning: (n: number) => (n === 1 ? '1 app · running' : `${n} apps · all running`),
  appsSomeRunning: (running: number, n: number) => `${running} of ${n} running`,
  noAppsShared: 'No apps shared yet',
  askFor: (admin: string) => `Ask ${admin} if you need another app`,
  askAdmin: 'Ask your admin if you need another app',
  browseStore: 'Browse the App Store',
  retry: 'Try again',
  /** What a tile says while its app is between states (US-HOME-06). */
  tileStatus: {
    starting: 'Starting…',
    restarting: 'Restarting…',
    stopping: 'Stopping…',
    rollingBack: 'Rolling back…',
    removing: 'Removing…',
  },
  /** A stopped or broken app's tile (US-HOME-08). */
  recover: {
    stopped: (app: string) => `${app} is stopped`,
    start: 'Start',
    starting: (app: string) => `Starting ${app}…`,
    askAdmin: (app: string, admin: string | null) =>
      `${app} isn't running right now. Ask ${admin ?? 'an admin'} to start it.`,
  },
  /** A tile's menu (US-HOME-07). */
  menu: {
    open: 'Open',
    settings: 'Settings',
    logs: 'View logs',
    restart: 'Restart',
    stop: 'Stop',
    start: 'Start',
    uninstall: 'Uninstall…',
    restarted: (app: string) => `${app} restarted`,
    started: (app: string) => `${app} started`,
    stopped: (app: string) => `${app} stopped`,
  },
  greeting: {
    morning: (name: string) => `Good morning, ${name}`,
    afternoon: (name: string) => `Good afternoon, ${name}`,
    evening: (name: string) => `Good evening, ${name}`,
  },
} as const;
