// Installing an app: the install sheet, the progress page and what a failed install says (US-STORE-08…14).
import type { InstallStep } from '@hlabs/api';

export const installCopy = {
  // Install sheet
  title: (app: string) => `Install ${app}`,
  subtitle: 'Review what it can access',
  folders: 'Folder access',
  home: 'Home',
  shared: 'Shared',
  appData: 'App data',
  place: (parts: string[]) => parts.filter(Boolean).join(' › '),
  folderMode: { rw: 'Read and write', ro: 'Read only' },
  useFolder: (label: string) => `Give access to ${label}`,
  noDefault: 'Choose a folder when Files arrives. For now this app needs a default location.',
  offline: (place: string) => `${place} is offline`,
  includes: 'Includes',
  roleWeb: 'web app',
  roleDatabase: 'database · private to this app',
  roleCache: 'cache · private to this app',
  rolePrivate: 'private to this app',
  server: (app: string) => `${app} server`,
  address: 'Address',
  addressLabel: 'App address',
  addressHint: 'The part before the dot is yours to change.',
  addressInvalid: 'Use lowercase letters, numbers and dashes',
  addressTaken: 'Another app already uses this address',
  loginRequired: 'Login required',
  noLogin: 'No hlabs login',
  ownLoginToo: 'Uses its own login too',
  settings: 'Settings',
  required: 'Required',
  number: 'Enter a number',
  showSecret: 'Show',
  hideSecret: 'Hide',
  risks: 'This app asks for more access',
  riskDocker: 'It can control Docker, so it can start, stop and change every app on hlabs.',
  riskPort: (label: string, port: number) => `It opens port ${port} (${label}) to your network.`,
  riskGpu: 'It uses your graphics card.',
  understand: 'I understand',
  cancel: 'Cancel',
  install: 'Install',
  askAdmin: 'Ask an admin to install this app',
  couldNotStart: "The install couldn't start. Check the details and try again.",

  // Progress and failure
  docTitle: (app: string) => `Installing ${app} · hlabs`,
  installing: (pct: number) => `Installing… ${pct}%`,
  waiting: 'Waiting for another app to finish…',
  minutesLeft: (m: number) => `About ${m} ${m === 1 ? 'minute' : 'minutes'} left`,
  underAMinute: 'Less than a minute left',
  canLeave: (app: string) => `You can leave this page. ${app} appears on your Home screen when it's ready.`,
  steps: 'Install steps',
  step: {
    check: { todo: 'Checking compatibility', done: 'Checked compatibility' },
    pull: { todo: 'Downloading images', done: 'Downloaded images' },
    folders: { todo: 'Creating data folders', done: 'Created data folders' },
    start: { todo: 'Starting containers', done: 'Started containers' },
    network: { todo: (a: string) => `Setting up ${a}`, done: (a: string) => `Set up ${a}` },
  },
  imagesFound: (arch: string) => `${arch} images found`,
  nOfM: (n: number, m: number) => `${n} of ${m}`,
  stepFailed: 'Failed',
  stepDone: (label: string) => `${label}, done`,
  ready: (app: string) => `${app} is ready`,
  open: 'Open',
  failed: 'Install failed',
  nothingChanged: 'Nothing else was changed',
  reason: {
    APP_PORT_IN_USE: (port: number | string) => `Port ${port} is already used by another program on this computer.`,
    APP_NO_PLATFORM: {
      macos: "There's no Apple Silicon version of this app.",
      linux: "There's no ARM64 version of this app.",
    },
    APP_DISK_FULL: (gb: string) => `Not enough free space. Needs ${gb} GB.`,
    APP_NETWORK_UNREACHABLE: "hlabs couldn't reach the internet to download the app.",
    APP_HEALTH_TIMEOUT: (app: string, seconds: number | string) => `${app} didn't start within ${seconds} seconds.`,
    crashed: (app: string) => `${app} stopped while starting.`,
    ENGINE_UNAVAILABLE: 'The container engine stopped.',
    restarted: 'hlabs restarted during the install.',
    other: 'Something went wrong while installing.',
  },
  useDifferentPort: 'Use a different port',
  tryAgain: 'Try again',
  backToStore: 'Back to App Store',
  openEngine: 'Open Engine settings',
  removePartial: 'Remove partial install',
  removeTitle: (app: string) => `Remove ${app}?`,
  removeBody: 'Any containers and data it created are deleted. Folders you chose, like your Photos, stay as they are.',
  remove: 'Remove',
  removing: 'Removing…',
  removed: (app: string) => `${app} was removed`,
  portTitle: 'Use a different port',
  portBody: 'hlabs reaches the app on this port on this computer. Pick a free one from 12000 to 12999.',
  portLabel: 'Port',
  portRange: 'Choose a port from 12000 to 12999',
  portTaken: 'That port is in use too. Try another.',
  retry: 'Try again',
} as const;

export type StepCopy = (typeof installCopy)['step'][InstallStep];
