// AcceptInvite (03-sign-in.md F-AUTH-09): the page an invite link opens.
export const inviteCopy = {
  docTitle: 'Join hlabs',
  invitedYou: (inviter: string) => `${inviter} invited you to`,
  someoneInvitedYou: "You've been invited to",
  product: 'hlabs · home cloud',
  title: 'Create your account',
  youGet: "You'll get your own Home screen and a private Files folder.",
  shared: (inviter: string, n: number) => `${inviter} has shared ${n === 1 ? '1 app' : `${n} apps`} with you.`,
  youreAdmin: "You'll be an admin and can open every app.",
  invalidTitle: "This invite doesn't work anymore",
  askFor: (inviter: string | null) => `Ask ${inviter ?? 'your admin'} for a new link.`,
  goToLogIn: 'Go to log in',
  loggedInAs: (username: string) => `You're logged in as @${username}.`,
  logOutAndContinue: 'Log out and continue',
  yourName: 'Your name',
  yourNamePlaceholder: 'First name',
  username: 'Username',
  usernamePlaceholder: 'lowercase, e.g. anu',
  usernameInvalid: 'Use 3–32 lowercase letters, numbers and dashes, starting with a letter.',
  usernameTaken: 'That username is taken.',
  password: 'Password',
  passwordPlaceholder: 'At least 12 characters',
  passwordTooShort: 'Use at least 12 characters.',
  passwordTooCommon: 'This password is too common. Try a longer phrase.',
  nameRequired: 'Enter your name.',
  join: 'Join hlabs',
  worksOnce: 'This invite link works once and expires in 7 days.',
  joinFailed: "Couldn't create your account. Try again.",
  locked: (minutes: number) => `Too many tries. Try again in ${minutes} ${minutes === 1 ? 'minute' : 'minutes'}.`,
  previewBanner: "Preview. This won't use up the invite.",
  loadFailed: "Couldn't open this invite. Check your connection and try again.",
  tryAgain: 'Try again',
} as const;
