// Words for signing in (docs/features/03-sign-in.md). Sentence case, plain words.
export const loginCopy = {
  usersTitle: "Who's using hlabs?",
  usersLead: 'Choose your account to log in',
  usersLabel: 'Accounts',
  usersFooter: 'Admins can hide this list in Settings › Users',
  otherUser: 'Other user',
  otherUserDetail: 'Enter username',
  roles: { admin: 'Admin', member: 'Member' },
  userName: (displayName: string, role: string) => `${displayName}, ${role}`,
  allUsers: 'All users',
  notYou: (displayName: string) => `Not ${displayName}? Use another account`,
  welcomeBack: (displayName: string) => `Welcome back, ${displayName}`,
  who: (username: string, role: string) => `@${username} · ${role}`,
  usernameTitle: 'Log in to hlabs',
  usernameLead: 'Use the username your admin gave you',
  username: 'Username',
  usernamePlaceholder: 'e.g. hari',
  password: 'Password',
  remember: 'Remember me on this device',
  logIn: 'Log in',
  forgot: 'Forgot password?',
  /** US-AUTH-20: ForgotPassword. No recovery-code option: those replace two-factor only (D-009, US-AUTH-21). */
  forgotTitle: 'Reset your password',
  forgotLead: "hlabs doesn't use email, so resets happen at home.",
  forgotWays: 'Ways to reset a password',
  askAdmin: 'Ask your admin',
  askAdminText: 'Family members: your admin can make a reset link for you from Settings › Users.',
  desktopAdmin: 'Admin on a Mac or Linux desktop',
  desktopAdminBefore: 'On the computer running hlabs, open the hlabs menu-bar icon and choose ',
  desktopAdminItem: 'Reset a password…',
  desktopAdminAfter: ". You'll confirm with that computer's own login.",
  serverAdmin: 'Admin on a Linux server',
  serverAdminText: 'Connect to the server and run',
  resetCommand: (username: string | undefined) => `sudo hlabs reset-password ${username || '<username>'}`,
  copyCommand: 'Copy command',
  copied: 'Copied',
  backToLogIn: 'Back to log in',
  /** US-AUTH-22: ResetLink. */
  resetTitle: 'Choose a new password',
  resetLead: 'This link came from your admin.',
  newPassword: 'New password',
  setPassword: 'Set password',
  resetStrong: 'Strong · at least 12 characters',
  resetTooShort: 'Use at least 12 characters.',
  resetTooCommon: 'This password is too common. Try a longer phrase.',
  resetExpiredTitle: 'This link has expired',
  resetExpired: 'This link has expired. Ask your admin for a new one.',
  resetFailed: "The password wasn't changed. Try again.",
  resetNote:
    'This link works once and expires 15 minutes after your admin made it. Your other devices will be signed out.',
  wrongDetails: 'Username or password is incorrect.',
  wrongPassword: 'Password is incorrect.',
  unreachable: "Can't reach hlabs right now. Try again in a moment.",
  failed: "Couldn't log in. Try again.",
  lockedTitle: 'Too many attempts',
  lockedLead: 'For your security, logging in as',
  lockedLeadEnd: 'is paused.',
  lockedLeadNoUser: 'For your security, logging in is paused for a while.',
  tryAgainIn: (time: string) => `Try again in ${time}`,
  tryAgain: 'Try again',
  timeLeft: 'Time left',
  useAnother: 'Use another account',
  loggedOutHere: 'You were logged out on this device.',
  adminNotified: 'The admin gets a notification about repeated failed logins.',
  timedOut: 'Your login timed out. Enter your password again.',
  codeTitle: 'Enter your code',
  codeLead: 'Open your authenticator app and type the 6-digit code for hlabs.',
  codeLabel: '6-digit code',
  verify: 'Verify',
  back: 'Back',
  useRecovery: 'Use a recovery code',
  useApp: 'Use my authenticator app',
  recoveryLabel: 'Recovery code',
  recoveryPlaceholder: 'xxxx-xxxx',
  wrongCode: "That code didn't work. Check the time on your phone and try again.",
  wrongRecovery: "That recovery code didn't work.",
  recoveryUsed: (left: number) => `Recovery code used. You have ${left} left.`,
  recoveryLow: 'Make new codes in Settings › Account.',
  manageCodes: 'Make new codes',
  cantCheck: "hlabs can't check codes right now. Use a recovery code or ask your admin.",
  secure: (host: string) => `${host} · secured with HTTPS`,
} as const;
