// Words for signing in (docs/features/03-sign-in.md). Sentence case, plain words.
export const loginCopy = {
  usersTitle: "Who's using hlabs?",
  usersLead: 'Choose your account to log in',
  usersLabel: 'Accounts',
  usersFooter: 'Admins can hide this list in Settings › Users',
  otherUser: 'Other user',
  otherUserDetail: 'Enter username',
  roles: { admin: 'Admin', member: 'Member' },
  userName: (displayName: string, role: string) => `${displayName}, ${role}`,
  allUsers: 'All users',
  notYou: (displayName: string) => `Not ${displayName}? Use another account`,
  welcomeBack: (displayName: string) => `Welcome back, ${displayName}`,
  who: (username: string, role: string) => `@${username} · ${role}`,
  usernameTitle: 'Log in to hlabs',
  usernameLead: 'Use the username your admin gave you',
  username: 'Username',
  usernamePlaceholder: 'e.g. hari',
  password: 'Password',
  remember: 'Remember me on this device',
  logIn: 'Log in',
  forgot: 'Forgot password?',
  wrongDetails: 'Username or password is incorrect.',
  wrongPassword: 'Password is incorrect.',
  unreachable: "Can't reach hlabs right now. Try again in a moment.",
  failed: "Couldn't log in. Try again.",
  lockedTitle: 'Too many attempts',
  secure: (host: string) => `${host} · secured with HTTPS`,
} as const;
