// Settings › Network & remote access (10-system-settings.md F-SYS-01).
export const networkCopy = {
  homeNetwork: 'Home network',
  localAddress: 'Local address',
  dnsName: (address: string) => `${address} · for devices that use your DNS server`,
  notPublished: 'Not published',
  useInstead: (address: string) => `Use ${address} until the name is published`,
  lanAddresses: (list: string) => `This computer on your network: ${list}`,
  rename: 'Rename',
  https: 'HTTPS on the home network',
  httpsHint: 'Install the hlabs certificate once on each device to remove browser warnings',
  getCertificate: 'Get certificate',
  webPorts: 'Web ports',
  ports: (http: number, https: number) => `HTTP ${http} · HTTPS ${https}`,
  portTaken: (port: number) => `${port} is used by another program`,
  change: 'Change',
  changePortsTitle: 'Change web ports',
  changePortsLead: 'hlabs and every app move to the new ports. Bookmarks with the old port stop working.',
  httpsPort: 'HTTPS port',
  httpPort: 'HTTP port',
  httpsPortHint: '443, or 1024–65535',
  httpPortHint: '80, or 1024–65535',
  portInUse: (port: number) => `Port ${port} is already in use by another program.`,
  portInvalid: 'Use 443 or 80, or a number from 1024 to 65535 outside 12000–13999.',
  portsSame: 'Choose two different ports.',
  appPortsTitle: 'Ports apps use',
  appPortLine: (app: string, label: string, protocol: string) => `${app} · ${label} · ${protocol.toUpperCase()}`,
  cancel: 'Cancel',
  save: 'Save',
  portsSaved: 'Web ports changed',
  movingTo: (address: string) => `Moving to ${address}…`,
  saveFailed: "Couldn't change the ports. Try again.",
  remoteAccess: 'Remote access',
  tailscale: 'Tailscale',
  notInstalled: 'Not installed',
  getTailscale: 'Get Tailscale',
  notRunning: "Tailscale isn't running",
  notRunningHint: 'Open the Tailscale app on this computer, then try again.',
  notConnected: 'Not connected',
  notConnectedHint: 'Reach hlabs from your phone or laptop away from home, with nothing exposed to the internet.',
  connect: 'Connect',
  waiting: 'Waiting for sign-in…',
  openLogin: 'Open the Tailscale log-in page',
  timedOut: 'Sign-in timed out. Try again.',
  connected: 'Connected',
  loggedOut: 'Tailscale is signed out on this computer',
  httpsOff: 'Turn on HTTPS certificates in your Tailscale admin console, then try again.',
  openAdminConsole: 'Open the admin console',
  needsPermission: 'Tailscale needs permission first',
  runOnce: 'Run this once on this computer, then try again:',
  operatorCommand: 'sudo tailscale set --operator=hlabs',
  copyCommand: 'Copy',
  commandCopied: 'Command copied',
  keyExpires: (date: string) =>
    `Tailscale will sign this computer out on ${date}. Renew the key in the Tailscale admin console.`,
  family: 'Adding family to your tailnet',
  openHelp: 'How to',
  confirmTitle: (tailnet: string) => `Publish hlabs on ${tailnet}?`,
  confirmBody: (address: string) =>
    `Everyone on this tailnet will be able to reach hlabs at ${address}. This computer keeps its name. If this is a work tailnet, connect a personal one instead.`,
  conflictTitle: 'Port 443 is already served on your tailnet',
  conflictBody:
    'Something else on this computer uses it with Tailscale Serve. hlabs never replaces it, but the dashboard can use port 8443 instead.',
  use8443: 'Use port 8443 for the dashboard',
  remoteOn: 'Remote access is on',
  connectFailed: "Couldn't connect remote access. Try again.",
  appAddresses: 'App addresses',
  noApps: 'No apps yet',
  openStore: 'Open the App Store',
  loadFailed: "Couldn't load how hlabs is reached.",
  tryAgain: 'Try again',
} as const;
