// Settings › Network & remote access (10-system-settings.md F-SYS-01).
export const networkCopy = {
  homeNetwork: 'Home network',
  localAddress: 'Local address',
  dnsName: (address: string) => `${address} · for devices that use your DNS server`,
  notPublished: 'Not published',
  useInstead: (address: string) => `Use ${address} until the name is published`,
  lanAddresses: (list: string) => `This computer on your network: ${list}`,
  rename: 'Rename',
  https: 'HTTPS on the home network',
  httpsHint: 'Install the hlabs certificate once on each device to remove browser warnings',
  getCertificate: 'Get certificate',
  webPorts: 'Web ports',
  ports: (http: number, https: number) => `HTTP ${http} · HTTPS ${https}`,
  portTaken: (port: number) => `${port} is used by another program`,
  change: 'Change',
  changePortsTitle: 'Change web ports',
  changePortsLead: 'hlabs and every app move to the new ports. Bookmarks with the old port stop working.',
  httpsPort: 'HTTPS port',
  httpPort: 'HTTP port',
  httpsPortHint: '443, or 1024–65535',
  httpPortHint: '80, or 1024–65535',
  portInUse: (port: number) => `Port ${port} is already in use by another program.`,
  portInvalid: 'Use 443 or 80, or a number from 1024 to 65535 outside 12000–14999.',
  portsSame: 'Choose two different ports.',
  appPortsTitle: 'Ports apps use',
  appPortLine: (app: string, label: string, protocol: string) => `${app} · ${label} · ${protocol.toUpperCase()}`,
  cancel: 'Cancel',
  save: 'Save',
  portsSaved: 'Web ports changed',
  movingTo: (address: string) => `Moving to ${address}…`,
  saveFailed: "Couldn't change the ports. Try again.",
  remoteAccess: 'Remote access',
  tailscale: 'Tailscale',
  notInstalled: 'Not installed',
  getTailscale: 'Get Tailscale',
  notRunning: "Tailscale isn't running",
  notRunningHint: 'Open the Tailscale app on this computer, then try again.',
  notConnected: 'Not connected',
  notConnectedHint: 'Reach hlabs from your phone or laptop away from home, with nothing exposed to the internet.',
  connect: 'Connect',
  waiting: 'Waiting for sign-in…',
  openLogin: 'Open the Tailscale log-in page',
  timedOut: 'Sign-in timed out. Try again.',
  connected: 'Connected',
  loggedOut: 'Tailscale is signed out on this computer',
  httpsOff: 'Turn on HTTPS certificates in your Tailscale admin console, then try again.',
  openAdminConsole: 'Open the admin console',
  needsPermission: 'Tailscale needs permission first',
  runOnce: 'Run this once on this computer, then try again:',
  operatorCommand: 'sudo tailscale set --operator=hlabs',
  copyCommand: 'Copy',
  commandCopied: 'Command copied',
  keyExpires: (date: string) =>
    `Tailscale will sign this computer out on ${date}. Renew the key in the Tailscale admin console.`,
  family: 'Adding family to your tailnet',
  openHelp: 'How to',
  confirmTitle: (tailnet: string) => `Publish hlabs on ${tailnet}?`,
  confirmBody: (address: string) =>
    `Everyone on this tailnet will be able to reach hlabs at ${address}. This computer keeps its name. If this is a work tailnet, connect a personal one instead.`,
  conflictTitle: 'Port 443 is already served on your tailnet',
  conflictBody:
    'Something else on this computer uses it with Tailscale Serve. hlabs never replaces it, but the dashboard can use port 8443 instead.',
  use8443: 'Use port 8443 for the dashboard',
  remoteOn: 'Remote access is on',
  disconnect: 'Disconnect',
  disconnectTitle: 'Turn off remote access?',
  disconnectBody: "People away from home can't open hlabs or its apps until you connect again.",
  disconnectHere: "You're using remote access right now. This page will stop working.",
  remoteOff: 'Remote access is off',
  connectFailed: "Couldn't connect remote access. Try again.",
  localDns: 'Local DNS server',
  changeDns: 'Change local DNS server',
  dnsHelper: "Point your router's DNS at it so every device uses it.",
  dnsNone: 'None',
  dnsAdguard: 'AdGuard Home on this computer',
  dnsAdguardHint: 'hlabs adds its names to AdGuard Home',
  dnsAdguardMissing: 'Install AdGuard Home from the App Store to use this',
  dnsAdguardLink: 'Get AdGuard Home',
  dnsPihole: 'Pi-hole',
  dnsPiholeHint: 'On this computer or another device, such as a Raspberry Pi',
  dnsPiholeAt: (address: string) => `Pi-hole at ${address}`,
  dnsManual: 'Another DNS server',
  dnsManualHint: 'You add the records yourself',
  piholeAddress: 'Pi-hole address',
  piholeAddressHint: 'For example http://192.168.1.10',
  piholePassword: 'App password',
  piholePasswordHint: 'Make one in Pi-hole under Settings › Web interface / API',
  piholePasswordKept: 'Leave empty to keep the saved password',
  test: 'Test',
  testOk: 'Pi-hole answered and accepted the password',
  addressInvalid: 'Enter an address that starts with http:// or https://',
  passwordNeeded: 'Enter an app password',
  notAnswering: (server: string) => `${server} isn't answering`,
  refusedPassword: 'Pi-hole refused the password',
  records: 'Records to add',
  recordsHint: "They change if this computer's address on your network changes.",
  copyRecords: 'Copy records',
  recordsCopied: 'Records copied',
  noRecords: "This computer has no address on your network yet. The records appear once it's connected.",
  dnsSaved: 'Local DNS server saved',
  copyFailed: "Couldn't copy. Select the text and copy it instead.",
  subnetOption: 'I reach my home network through a Tailscale subnet router',
  subnetOptionHint: "For example on a Raspberry Pi. Tailscale isn't needed on this computer.",
  useSubnetRouter: 'Use subnet router',
  throughSubnetRouter: 'Through your subnet router',
  throughSubnetRouterHint: 'Devices on your tailnet reach hlabs at its home-network address.',
  useTailscaleHere: 'Use Tailscale on this computer instead',
  subnetSaved: 'hlabs is reached through your subnet router',
  subnetHelp: 'Set up names and certificates for your tailnet',
  noLanAddress: 'This computer has no address on your network yet.',
  modeFailed: "Couldn't change how hlabs is reached. Try again.",
  dashboard: 'Dashboard',
  appAddresses: 'App addresses',
  noApps: 'No apps yet',
  openStore: 'Open the App Store',
  loadFailed: "Couldn't load how hlabs is reached.",
  tryAgain: 'Try again',
} as const;
