// Words for onboarding (docs/features/02-onboarding.md). Sentence case, plain words.
export const onboardingCopy = {
  welcomeTitle: 'Welcome to hlabs',
  welcomeSubtitle: 'Your own cloud, running on this computer.',
  getStarted: 'Get started',
  setupTime: 'Setup takes about five minutes',
  startFailed: "Couldn't start setup. Try again.",
  back: 'Back',
  continue: 'Continue',
  system: {
    lead: "hlabs runs apps in containers. We'll set up anything that's missing.",
    checking: 'Checking…',
    processor: 'Processor',
    appleSilicon: 'Apple Silicon',
    os: 'Operating system',
    runtime: 'Container runtime',
    runtimeMissing: 'Not found',
    installing: (percent: number) => `Installing Colima… ${percent}%`,
    installNote: 'No Docker found. OrbStack or Docker Desktop are used automatically when present.',
    failedTitle: 'Something needs attention',
    failedLead: "We couldn't set up the container runtime. Nothing has been changed on this computer.",
    installFailed: 'Install failed',
    installHints: {
      ENGINE_DOWNLOAD_TIMEOUT: 'Check your internet connection and try again.',
      ENGINE_START_FAILED: "Colima couldn't start. Try again, or restart this Mac and try again.",
      other: 'Try again. If it keeps failing, open the full log.',
    },
    retry: 'Retry',
    viewLog: 'View full log',
    logTitle: 'Container runtime install log',
    logEmpty: 'The log is empty.',
    copy: 'Copy',
    copied: 'Copied',
    close: 'Close',
    otherRuntimeTip:
      'Already use Docker? Install OrbStack or Docker Desktop and press Retry, and hlabs will use it instead.',
    runtimeStopped: (name: string) => `${name} is not running`,
    stoppedHint: (name: string) => `Start ${name}, then press Retry.`,
    runtimeNoAccess: 'No access',
    noAccessHint:
      "Your account isn't allowed to use Docker yet. Add it to the docker group with this command, log out and back in, then press Retry.",
    dockerGroupCommand: 'sudo usermod -aG docker $USER',
    linuxMissingHint:
      "Install Docker Engine with this command in a terminal, then press Retry. hlabs doesn't run it for you.",
    linuxInstallCommand: 'curl -fsSL https://get.docker.com | sh',
    copyCommand: 'Copy command',
    startAtLogin: 'Start hlabs when I log in',
    startAtLoginHint: 'Keeps your apps running in the background from the menu bar',
    disk: 'Free disk space',
    diskError: 'hlabs needs at least 10 GB free. Free up some space, then check again.',
    diskWarning: 'Less than 30 GB free. Apps and files can fill this quickly.',
    ports: 'Ports 80 and 443',
    port: (port: number) => `Port ${port}`,
    available: 'Available',
    inUse: (fallbacks: string) => `In use · will use ${fallbacks}`,
    and: (a: string, b: string) => `${a} and ${b}`,
    checkAgain: 'Check again',
    checkFailed: "Couldn't check this computer. Check again.",
    continueFailed: {
      ENGINE_UNAVAILABLE: 'The container runtime stopped. Start it, then check again.',
      DISK_FULL: 'hlabs needs at least 10 GB free. Free up some space, then check again.',
      other: "Couldn't save this step. Try again.",
    },
    engines: {
      orbstack: 'OrbStack',
      'docker-desktop': 'Docker Desktop',
      colima: 'Colima',
      'docker-engine': 'Docker Engine',
    },
  },
  account: {
    lead: 'The admin manages apps, users and settings. You can add family members later.',
    name: 'Your name',
    username: 'Username',
    password: 'Password',
    confirm: 'Confirm password',
    show: 'Show password',
    hide: 'Hide password',
    passwordEmpty: 'At least 12 characters',
    passwordWeak: 'Weak · use at least 12 characters',
    passwordCommon: 'This password is too common',
    passwordStrong: 'Strong · at least 12 characters',
    strength: 'Password strength',
    create: 'Create account',
    failed: "Couldn't create the account. Try again.",
    nameMissing: 'Enter your name',
    adminExists: 'An admin account already exists. Log in to continue.',
    logIn: 'Log in',
    usernameInvalid: 'Use 3–32 lowercase letters, numbers and dashes, starting with a letter, e.g. hari',
    usernameTaken: 'That username is already taken. Choose another.',
    confirmMismatch: "Passwords don't match",
    fixCount: (n: number) => `Fix ${n} ${n === 1 ? 'thing' : 'things'} to continue.`,
  },
  twoFactor: {
    recommended: 'Recommended',
    lead: 'Scan with an authenticator app, then enter the 6-digit code it shows.',
    qrAlt: 'QR code for your authenticator app',
    cantScan: "Can't scan? Enter this key instead",
    key: 'Setup key',
    copyKey: 'Copy key',
    apps: 'Works with any TOTP app, such as 1Password, Google Authenticator or Authy.',
    codeLabel: '6-digit code',
    turnOn: 'Turn on',
    wrongCode: "That code didn't work. Check the time on your phone and try again.",
    locked: 'Too many codes that didn’t work. Try again in 15 minutes.',
    setupFailed: "Couldn't start two-factor setup. Reload the page to try again.",
    codesTitle: 'Two-factor is on',
    skipForNow: 'Skip for now',
    skipTitle: 'Skip two-factor login?',
    skipWarning: 'Anyone who learns your password can manage hlabs. You can turn on two-factor later in Account.',
    skip: 'Skip',
    setUpNow: 'Set up now',
    codesLabel: 'Recovery codes',
    codesWarning: "Save these somewhere safe. Each code works once and you won't see them again.",
    download: 'Download',
    copyCodes: 'Copy',
    alreadyOn: 'You can make new recovery codes later in Account settings.',
    continueFailed: "Couldn't save this step. Try again.",
    file: {
      title: 'hlabs recovery codes',
      server: 'Server',
      username: 'Username',
      created: 'Created',
      note: 'Each code works once, in place of a two-factor code when you log in. Keep them somewhere safe.',
    },
  },
  storage: {
    lead: 'Home folders, shared files and media go here. You can move them later in Settings.',
    listLabel: 'Storage location',
    local: 'This computer',
    localDetail: (path: string, free: string) => `${path} · ${free} free`,
    fastest: 'Fastest',
    external: 'External drive',
    externalDetail: 'Choose a connected USB or Thunderbolt drive',
    nas: 'Network storage (NAS)',
    nasDetail: 'SMB or NFS share, best for media and backups',
    note: 'App databases always stay on this computer for speed. Media libraries can point anywhere.',
    drivesLabel: 'Connected drives',
    noDrives: 'Connect a drive to see it here.',
    driveDetail: (free: string, fs: string) => `${free} free · ${fs}`,
    noPermissions: "This drive's format doesn't support file permissions. Some apps may not work.",
    driveGone: 'That drive was disconnected. Connect it again, or choose another.',
    nasForm: {
      protocol: 'Protocol',
      address: 'Address',
      addressHint: 'For example nas.local/media',
      username: 'Username',
      password: 'Password',
      testing: 'Testing the connection…',
      badAddress: 'Enter the address as name/share, for example nas.local/media',
      unreachable: (host: string) => `Can't reach ${host}. Check the address and that the NAS is on.`,
      noShare: (share: string, host: string) => `There's no share called “${share}” on ${host}.`,
      privilegedPort:
        'This NAS only accepts connections from system ports. Allow non-privileged ports ("insecure") in its NFS settings, or use SMB.',
      authFailed: 'Wrong username or password.',
      readOnly: 'hlabs can only read this share. Let this user write to it, then try again.',
      helperMissing: "hlabs can't connect network storage on this computer yet.",
    },
    fsNames: {
      apfs: 'APFS',
      hfs: 'Mac OS Extended',
      exfat: 'exFAT',
      fat32: 'FAT32',
      ntfs: 'NTFS',
      ext4: 'ext4',
      btrfs: 'Btrfs',
      xfs: 'XFS',
      other: 'Other format',
    },
    notWritable: (path: string) => `hlabs can't write to ${path}. Check the folder's permissions, then try again.`,
    failed: "Couldn't save where your data lives. Try again.",
  },
  done: {
    title: (firstName: string) => (firstName ? `You're all set, ${firstName}` : "You're all set"),
    appsInstalling: 'Your apps are installing.',
    menuBar: 'hlabs keeps running from the menu bar.',
    background: 'hlabs keeps running in the background.',
    summary: 'What was set up',
    admin: 'Admin account',
    adminDetail: (username: string, totp: boolean) => `${username} · 2FA ${totp ? 'on' : 'off'}`,
    storage: 'Storage',
  },
  stepNames: {
    system: 'System check',
    account: 'Admin account',
    twoFactor: 'Two-factor login',
    storage: 'Storage',
    remote: 'Remote access',
    apps: 'Starter apps',
  },
  titles: {
    system: 'Checking this computer',
    account: 'Create your admin account',
    twoFactor: 'Add two-factor login',
    storage: 'Where should your data live?',
    done: "You're all set",
  },
  finishOnHost: 'Finish setup on the computer running hlabs.',
} as const;
