// Words for onboarding (docs/features/02-onboarding.md). Sentence case, plain words.
export const onboardingCopy = {
  welcomeTitle: 'Welcome to hlabs',
  welcomeSubtitle: 'Your own cloud, running on this computer.',
  getStarted: 'Get started',
  setupTime: 'Setup takes about five minutes',
  startFailed: "Couldn't start setup. Try again.",
  back: 'Back',
  continue: 'Continue',
  system: {
    lead: "hlabs runs apps in containers. We'll set up anything that's missing.",
    checking: 'Checking…',
    processor: 'Processor',
    appleSilicon: 'Apple Silicon',
    os: 'Operating system',
    runtime: 'Container runtime',
    runtimeMissing: 'Not found',
    runtimeStopped: (name: string) => `${name} isn't running`,
    disk: 'Free disk space',
    diskError: 'hlabs needs at least 10 GB free. Free up some space, then check again.',
    diskWarning: 'Less than 30 GB free. Apps and files can fill this quickly.',
    ports: 'Ports 80 and 443',
    port: (port: number) => `Port ${port}`,
    available: 'Available',
    inUse: (fallbacks: string) => `In use · will use ${fallbacks}`,
    and: (a: string, b: string) => `${a} and ${b}`,
    checkAgain: 'Check again',
    checkFailed: "Couldn't check this computer. Check again.",
    continueFailed: {
      ENGINE_UNAVAILABLE: 'The container runtime stopped. Start it, then check again.',
      DISK_FULL: 'hlabs needs at least 10 GB free. Free up some space, then check again.',
      other: "Couldn't save this step. Try again.",
    },
    engines: {
      orbstack: 'OrbStack',
      'docker-desktop': 'Docker Desktop',
      colima: 'Colima',
      'docker-engine': 'Docker Engine',
    },
  },
  stepNames: {
    system: 'System check',
    account: 'Admin account',
    twoFactor: 'Two-factor login',
    storage: 'Storage',
    remote: 'Remote access',
    apps: 'Starter apps',
  },
  titles: {
    system: 'Checking this computer',
    account: 'Create your admin account',
    twoFactor: 'Add two-factor login',
    storage: 'Where should your data live?',
    done: "You're all set",
  },
  finishOnHost: 'Finish setup on the computer running hlabs.',
} as const;
