// Words for onboarding (docs/features/02-onboarding.md). Sentence case, plain words.
export const onboardingCopy = {
  welcomeTitle: 'Welcome to hlabs',
  welcomeSubtitle: 'Your own cloud, running on this computer.',
  getStarted: 'Get started',
  setupTime: 'Setup takes about five minutes',
  startFailed: "Couldn't start setup. Try again.",
  back: 'Back',
  continue: 'Continue',
  system: {
    lead: "hlabs runs apps in containers. We'll set up anything that's missing.",
    checking: 'Checking…',
    processor: 'Processor',
    appleSilicon: 'Apple Silicon',
    os: 'Operating system',
    runtime: 'Container runtime',
    runtimeMissing: 'Not found',
    installing: (percent: number) => `Installing Colima… ${percent}%`,
    installNote: 'No Docker found. OrbStack or Docker Desktop are used automatically when present.',
    failedTitle: 'Something needs attention',
    failedLead: "We couldn't set up the container runtime. Nothing has been changed on this computer.",
    installFailed: 'Install failed',
    installHints: {
      ENGINE_DOWNLOAD_TIMEOUT: 'Check your internet connection and try again.',
      ENGINE_START_FAILED: "Colima couldn't start. Try again, or restart this Mac and try again.",
      other: 'Try again. If it keeps failing, open the full log.',
    },
    retry: 'Retry',
    viewLog: 'View full log',
    logTitle: 'Container runtime install log',
    logEmpty: 'The log is empty.',
    copy: 'Copy',
    copied: 'Copied',
    close: 'Close',
    otherRuntimeTip:
      'Already use Docker? Install OrbStack or Docker Desktop and press Retry, and hlabs will use it instead.',
    runtimeStopped: (name: string) => `${name} is not running`,
    stoppedHint: (name: string) => `Start ${name}, then press Retry.`,
    runtimeNoAccess: 'No access',
    noAccessHint:
      "Your account isn't allowed to use Docker yet. Add it to the docker group with this command, log out and back in, then press Retry.",
    dockerGroupCommand: 'sudo usermod -aG docker $USER',
    linuxMissingHint:
      "Install Docker Engine with this command in a terminal, then press Retry. hlabs doesn't run it for you.",
    linuxInstallCommand: 'curl -fsSL https://get.docker.com | sh',
    copyCommand: 'Copy command',
    startAtLogin: 'Start hlabs when I log in',
    startAtLoginHint: 'Keeps your apps running in the background from the menu bar',
    disk: 'Free disk space',
    diskError: 'hlabs needs at least 10 GB free. Free up some space, then check again.',
    diskWarning: 'Less than 30 GB free. Apps and files can fill this quickly.',
    ports: 'Ports 80 and 443',
    port: (port: number) => `Port ${port}`,
    available: 'Available',
    inUse: (fallbacks: string) => `In use · will use ${fallbacks}`,
    and: (a: string, b: string) => `${a} and ${b}`,
    checkAgain: 'Check again',
    checkFailed: "Couldn't check this computer. Check again.",
    continueFailed: {
      ENGINE_UNAVAILABLE: 'The container runtime stopped. Start it, then check again.',
      DISK_FULL: 'hlabs needs at least 10 GB free. Free up some space, then check again.',
      other: "Couldn't save this step. Try again.",
    },
    engines: {
      orbstack: 'OrbStack',
      'docker-desktop': 'Docker Desktop',
      colima: 'Colima',
      'docker-engine': 'Docker Engine',
    },
  },
  account: {
    lead: 'The admin manages apps, users and settings. You can add family members later.',
    name: 'Your name',
    username: 'Username',
    password: 'Password',
    confirm: 'Confirm password',
    show: 'Show password',
    hide: 'Hide password',
    passwordEmpty: 'At least 12 characters',
    passwordWeak: 'Weak · use at least 12 characters',
    passwordCommon: 'This password is too common',
    passwordStrong: 'Strong · at least 12 characters',
    strength: 'Password strength',
    create: 'Create account',
    failed: "Couldn't create the account. Try again.",
    nameMissing: 'Enter your name',
    usernameInvalid: 'Use 3–32 lowercase letters, numbers and dashes, starting with a letter, e.g. hari',
    usernameTaken: 'That username is already taken. Choose another.',
    confirmMismatch: "Passwords don't match",
    fixCount: (n: number) => `Fix ${n} ${n === 1 ? 'thing' : 'things'} to continue.`,
  },
  stepNames: {
    system: 'System check',
    account: 'Admin account',
    twoFactor: 'Two-factor login',
    storage: 'Storage',
    remote: 'Remote access',
    apps: 'Starter apps',
  },
  titles: {
    system: 'Checking this computer',
    account: 'Create your admin account',
    twoFactor: 'Add two-factor login',
    storage: 'Where should your data live?',
    done: "You're all set",
  },
  finishOnHost: 'Finish setup on the computer running hlabs.',
} as const;
