// Settings › Users (09-account-people.md F-ACCT-05…08). Sentence case, plain words.
export const peopleCopy = {
  people: (n: number) => `People · ${n}`,
  invite: 'Invite someone',
  you: '(you)',
  roles: { admin: 'Admin', member: 'Member' },
  disabled: 'Disabled',
  totpOn: '2FA on',
  totpOff: '2FA off',
  lastActive: (when: string) => `last active ${when}`,
  activeNow: 'active now',
  neverActive: 'not logged in yet',
  apps: (n: number) => (n === 1 ? '1 app' : `${n} apps`),
  appsAccess: 'Apps access',
  resetPassword: 'Reset password',
  moreOptions: (name: string) => `More options for ${name}`,
  makeAdmin: 'Make admin',
  makeMember: 'Make member',
  disable: 'Disable',
  enable: 'Enable',
  delete: 'Delete…',
  invitePending: 'Invite pending',
  inviteLine: (created: string, days: number, role: string) =>
    `Link created ${created} · expires in ${days === 1 ? '1 day' : `${days} days`} · ${role}`,
  copyLink: 'Copy link',
  revoke: 'Revoke',
  inviteTitle: 'Invite someone',
  theirName: 'Their name (optional)',
  theirNamePlaceholder: 'Shown on the invite page',
  inviteLink: 'Invite link',
  copy: 'Copy',
  copied: 'Copied',
  worksOnce: 'Works once · expires in 7 days ·',
  close: 'Close',
  done: 'Done',
  creatingLink: 'Making a link…',
  createFailed: "Couldn't make an invite link. Try again.",
  copyFailed: "Couldn't copy the link. Select it and copy it yourself.",
  saveFailed: "Couldn't save that change. Try again.",
  loadFailed: "Couldn't load the people who use hlabs.",
  tryAgain: 'Try again',
} as const;
