// Settings › Users (09-account-people.md F-ACCT-05…08). Sentence case, plain words.
export const peopleCopy = {
  people: (n: number) => `People · ${n}`,
  invite: 'Invite someone',
  you: '(you)',
  roles: { admin: 'Admin', member: 'Member' },
  disabled: 'Disabled',
  totpOn: '2FA on',
  totpOff: '2FA off',
  lastActive: (when: string) => `last active ${when}`,
  activeNow: 'active now',
  neverActive: 'not logged in yet',
  apps: (n: number) => (n === 1 ? '1 app' : `${n} apps`),
  appsAccess: 'Apps access',
  resetPassword: 'Reset password',
  moreOptions: (name: string) => `More options for ${name}`,
  makeAdmin: 'Make admin',
  makeMember: 'Make member',
  disable: 'Disable',
  enable: 'Enable',
  delete: 'Delete…',
  makeAdminTitle: (name: string) => `Make ${name} an admin?`,
  makeAdminBody: (name: string) => `${name} will be able to change everything.`,
  makeMemberTitle: (name: string) => `Make ${name} a member?`,
  makeMemberBody: (name: string) => `${name} will only open the apps you share with them.`,
  disableTitle: (name: string) => `Disable ${name}?`,
  disableBody:
    "They're logged out everywhere and can't log in until you enable them. Their account and files are kept.",
  roleChanged: (name: string, role: string) => `${name} is now ${role === 'Admin' ? 'an admin' : 'a member'}`,
  disabledToast: (name: string) => `${name} is disabled`,
  enabledToast: (name: string) => `${name} can log in again`,
  deleteTitle: (name: string) => `Delete ${name}?`,
  deleteBody: (name: string) =>
    `${name} is logged out and their account, two-factor login and app access are removed. Their apps keep running for everyone else.`,
  deleteHomeFolder: (size: string) => `Also delete their Home folder (${size})`,
  deleteHomeFolderCounting: 'Also delete their Home folder (counting…)',
  keptHomeFolder: (username: string) =>
    `Their Home folder stays in users/${username}, where admins can see it in Files.`,
  trashedHomeFolder: 'Their Home folder goes to the trash and is emptied after 30 days.',
  deleteConfirm: (name: string) => `Delete ${name}`,
  deleted: (name: string) => `${name} was deleted`,
  resetTitle: (name: string) => `Reset ${name}'s password`,
  resetLead: (name: string) =>
    `Give ${name} this link. They choose a new password, and they're logged out on every device.`,
  resetLink: 'Reset link',
  resetNote: 'Works once · expires in 15 minutes',
  resetFailed: "Couldn't make a reset link. Try again.",
  actionFailed: "Couldn't make that change. Try again.",
  invitePending: 'Invite pending',
  inviteLine: (created: string, days: number, role: string) =>
    `Link created ${created} · expires in ${days === 1 ? '1 day' : `${days} days`} · ${role}`,
  copyLink: 'Copy link',
  linkCopied: 'Link copied',
  revokeTitle: 'Revoke this invite?',
  revokeBody: "The link stops working straight away. Anyone who opens it is told it doesn't work anymore.",
  revoked: 'Invite revoked',
  revoke: 'Revoke',
  inviteTitle: 'Invite someone',
  theirName: 'Their name (optional)',
  theirNamePlaceholder: 'Shown on the invite page',
  role: 'Role',
  roleMember: 'Uses the apps you share',
  roleAdmin: 'Can change everything',
  appsTheyCanOpen: 'Apps they can open',
  adminsOpenEverything: 'Admins can open every app.',
  noAppsYet: 'No apps installed yet',
  inviteLink: 'Invite link',
  copy: 'Copy',
  copied: 'Copied',
  worksOnce: 'Works once · expires in 7 days ·',
  preview: 'Preview what they see',
  previewNewTab: 'Preview what they see (opens in a new tab)',
  close: 'Close',
  done: 'Done',
  creatingLink: 'Making a link…',
  createFailed: "Couldn't make an invite link. Try again.",
  copyFailed: "Couldn't copy the link. Select it and copy it yourself.",
  saveFailed: "Couldn't save that change. Try again.",
  accessTitle: (name: string) => `What ${name} can open`,
  accessLead: "Apps not shared don't appear on their Home screen",
  accessApps: (name: string) => `Apps ${name} can open`,
  ownLoginToo: 'Uses its own login too',
  openAppStore: 'Open the App Store',
  seeShared: 'See the Shared folder in Files',
  seeSharedHint: 'Their own Home folder is always private',
  seeUsage: 'See live usage',
  memberOptions: (name: string) => `What else ${name} can see`,
  cancel: 'Cancel',
  save: 'Save',
  saved: 'Saved',
  loadFailed: "Couldn't load the people who use hlabs.",
  tryAgain: 'Try again',
} as const;
